import { vi } from 'vitest';

vi.mock('../src/config/index.js', () => ({
  config: {
    LLM_PROVIDER: 'openai',
    OPENAI_API_KEY: 'test-key',
    ANTHROPIC_API_KEY: undefined,
    GOOGLE_GENERATIVE_AI_API_KEY: undefined,
    XAI_API_KEY: undefined,
    MISTRAL_API_KEY: undefined,
    GROQ_API_KEY: undefined,
    ZAI_API_KEY: undefined,
    OPENROUTER_API_KEY: undefined,
    SCORE_THRESHOLD: 7,
    TOP_N_SEGMENTS: 10,
    CHUNK_LENGTH_SEC: 120,
    CHUNK_OVERLAP_SEC: 20,
    MICRO_BLOCK_SEC: 15,
    LLM_MODEL: 'gpt-4o',
    LLM_MAX_RETRIES: 3,
    DOWNLOAD_DIR: 'downloads/',
    OUTPUT_DIR: 'outputs/',
    CACHE_DIR: 'outputs/cache',
    DUMP_OUTPUTS: false,
    MAX_CHUNKS: undefined,
    LLM_CONCURRENCY: 3,
    CLIP_CONCURRENCY: 1,
    LLM_SYSTEM_PROMPT: undefined,
    AUDIO_GEMINI_MODEL: 'gemini-2.5-flash',
    AUDIO_EXTRA_INSTRUCTIONS: undefined,
    DOWNLOAD_SECTIONS_MODE: 'all' as const,
    FFMPEG_PATH: undefined,
    FFPROBE_PATH: undefined,
    FFMPEG_PRESET: 'fast' as const,
    TIMESTAMP_OFFSET_SECONDS: 0,
    TRANSCRIPT_PROVIDER: 'ytdlp',
    AUDIO_DETECTION_ENABLED: true,
    AUDIO_PROVIDER: 'gemini,whisper',
    AUDIO_CONFIDENCE_THRESHOLD: 0.3,
    AUDIO_CLIP_PRE_ROLL: 5,
    AUDIO_CLIP_POST_ROLL: 15,
    AUDIO_LLM_BOOST_WINDOW: 10,
    AUDIO_LLM_SCORE_BOOST: 2,
    GAME_PROFILE: 'general' as const,
    YT_DLP_COOKIES_FROM_BROWSER: undefined,
    YT_DLP_COOKIES_FILE: undefined,
  },
}));
