import type { CaptionTemplate } from '@app/web/types/componentProps.js';

export const CAPTION_TEMPLATES: CaptionTemplate[] = [
  {
    id: 'bold-white',
    name: 'Bold White',
    style: {
      fontFamily: 'Inter',
      fontSize: 56,
      weight: 800,
      color: '#FFFFFF',
      highlightColor: '#FFD60A',
      bgColor: null,
      outlineColor: '#000000',
      outlineWidth: 3,
      align: 'center',
    },
    position: { xCenter: 0.5, yCenter: 0.85 },
  },
  {
    id: 'yellow-pop',
    name: 'Yellow Pop',
    style: {
      fontFamily: 'Inter',
      fontSize: 56,
      weight: 800,
      color: '#FFD60A',
      highlightColor: '#FFFFFF',
      bgColor: null,
      outlineColor: '#000000',
      outlineWidth: 3,
      align: 'center',
    },
    position: { xCenter: 0.5, yCenter: 0.85 },
  },
  {
    id: 'subtle',
    name: 'Subtle',
    style: {
      fontFamily: 'Inter',
      fontSize: 40,
      weight: 400,
      color: '#FFFFFF',
      highlightColor: '#FFD60A',
      bgColor: '#000000CC',
      outlineColor: null,
      outlineWidth: 0,
      align: 'center',
    },
    position: { xCenter: 0.5, yCenter: 0.9 },
  },
  {
    id: 'hooked',
    name: 'Hooked',
    style: {
      fontFamily: 'Inter',
      fontSize: 48,
      weight: 700,
      color: '#FFFFFF',
      highlightColor: '#FF4444',
      bgColor: null,
      outlineColor: '#000000',
      outlineWidth: 2,
      align: 'center',
    },
    position: { xCenter: 0.5, yCenter: 0.8 },
  },
  {
    id: 'karaoke',
    name: 'Karaoke',
    style: {
      fontFamily: 'Inter',
      fontSize: 48,
      weight: 700,
      color: '#FFFFFF',
      highlightColor: '#00BFFF',
      bgColor: null,
      outlineColor: '#000000',
      outlineWidth: 2,
      align: 'center',
    },
    position: { xCenter: 0.5, yCenter: 0.85 },
  },
];
